#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pa ebin

main([]) ->
	main(["priv/lsr/test.lsr", "test"]);
main([SrcFile, DstFile]) ->
	compile(SrcFile, DstFile, false);
main([SrcFile, DstFile, "debug"]) ->
	compile(SrcFile, DstFile, true);
main(_) ->
	io:format("Usage: lsrc [ SRC DST ]~n~n"
	          "By default, 'priv/lsr/test.lsr' is compiled to 'test'.~n").

compile(SrcFile, DstFile, Debug) ->
	{ok, Src} = file:read_file(SrcFile),
	case lsrc:compile(Src, Debug) of
		{ok, Dst} ->
			file:write_file([DstFile, ".c"], Dst),
			Output = os:cmd(["gcc -Wall -pedantic ", % -Wno-unused-label
			                 DstFile, ".c -o ", DstFile]),
			io:format("~s", [Output]);
		{error, Msg} ->
			io:format("~s~n", [Msg])
	end.
